spring:
  config:
    import: application-secrets.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
app:
  cors:
    allowedOrigins: http://localhost:3000, http://localhost:8080