spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprivedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
app:
  cors:
    allowedOrigins: http://localhost:3000, http://localhost:8080